# export installState=test
get:
	python cli.py get "https://github.com/tenable/terrascan"
	python cli.py get "https://github.com/Rishang/gnome-theme-installer"
	python cli.py get "https://github.com/tomnomnom/gron"
upgrade:
	python cli.py upgrade
ls:
	python cli.py ls
rm:
	python cli.py rm gron