name: Publish to PyPI
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build and Publish to PyPI
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}